### ISSUE TITLE
Allow compound words

### ISSUE THREAD

**Issue by luisvalenzuelar** [RoSh-23/Index-Creator#3]
Hi again, 

Code cannot search for compound words like "industrial revolution" or "well-being". Since such a search would be simple surely it is easy to implement. 

Code also does not allow trailing spaces in words (like "hello "). These are invisible in most text editors. Maybe this can be allowed too (or at least a warning given to the user).

best

**Comment by RoSh-23** [comment]
Thanks for your feedback.
I have mentioned some of the limitations you have listed, other limitations will be mentioned soon.
You are right in saying that the program should have the capability to search for compound words, but due to timing constraints,
I am unable to add that feature. You have mentioned that implementing this feature is easy, but in my opinion implementing such a search is not as straightforward as it seems. Any ideas from you will be appreciated.
Finally I would like to specify that this project was  made to practice and showcase data structures and file handling skills. But adding the capability for searching compound words is on agenda in the future if time permits.
